### ISSUE TITLE
Vineyard Code?

### ISSUE THREAD

**Issue by jcoll3** [MathieuCarriere/multipers#1]
Hello,

I have been interested in exploring the applications of vineyards, but I have not seen a public implementation.

Would it be possible to share any code?

Thanks!

-Joe

**Comment by MathieuCarriere** [comment]
Hi Joe! In this project, I compiled and used the implementation of Dmitriy Morozov: https://www.mrzv.org/software/dionysus/examples/pl-vineyard.html

Hope this helps!

Mathieu

**Comment by jcoll3** [comment]
Very helpful, thank you!
