### ISSUE TITLE
A question about compute the vineyards（sublevelsets_multipersistence）

### ISSUE THREAD

**Issue by shiqingzhangCSU** [MathieuCarriere/multipers#2]
I think your job is very meaningful and exciting！
I want to reproduce the experiments in the experiments.ipynb，but there seems to be a problem here
![image](https://user-images.githubusercontent.com/44834482/112564702-b1e60a80-8e16-11eb-862c-1433474a3f47.png)

![image](https://user-images.githubusercontent.com/44834482/112564644-9b3fb380-8e16-11eb-806c-fad3069698d7.png)
I don't know if there is a problem with the code？
I am looking for your reply！Thanks！

**Comment by MathieuCarriere** [comment]
Hi! Can you try running "cd bin && ./vine" in a terminal? Just to see if your OS supports the provided exec for vineyards.

**Comment by shiqingzhangCSU** [comment]
Thanks！The problem is I didnt have libboost_filesystem.so.1.65.1 in my OS. Now I solve the problem!!!!!!!
非常感谢你！！！

**Comment by MathieuCarriere** [comment]
Glad to hear its working now!
