### ISSUE TITLE
 How to reproduce the code related to immunofluorescence imaging?

### ISSUE THREAD

**Issue by HeJiaxing-hjx** [MathieuCarriere/multipers#3]
Your work is truly impressive and has inspired me to explore the field further.
I am particularly interested in the immunofluorescence imaging part of your study and was wondering if you could provide any guidance on how to replicate the code used in this section. I would greatly appreciate any help you could offer in this regard. 
Thank you for your time and consideration, and I look forward to hearing from you soon.

**Comment by MathieuCarriere** [comment]
Oops, sorry, just realized I didn't reply. Thanks for your interest in the code. Unfortunately, the data we used in this project for immunofluorescence imaging is protected and cannot be shared. But I strongly suggest you have a look at [this repo](https://github.com/DavidLapous/multipers), and its associated preprints, as it also contains experiments on public immunohistochemistry datasets.
